[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]
  included_files = ["netlify/functions/utils/**"]

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.ts"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.tsx"
    [headers.values]
    Content-Type = "application/javascript"
